package com.example.teminavigator.ui.langs

val englishStrings = AppStrings(
    acceptButton = "Take me there",
    confirmTitle = { name -> "Go to $name?" },
    confirmYes = "Yes, guide me",
    confirmNo = "Cancel",
    cdMap = "Floor map",
    cdSettings = "Settings",
    cdZoomIn = "Zoom in",
    cdZoomOut = "Zoom out",
    settingsTitle = "Settings",
    languageLabel = "Language",
    spokenArrived = { name -> "We have arrived at $name." },
    spokenUnknownDestination = "Sorry, I don't know that destination.",
    greeting = "Hello, nice to see you!",
    locationQuery = "Where can I get you?",
    selectLocation = "Select location",
    backToNavigation = "Back to navigation screen",
    speechNotice = "You can also say: \"Bring me to room 2.72\"",
    goingTo = "GOING TO",
    minutes = "minutes",
    pause =  "Pause",
    abortNavigation = "Abort navigation",
    simulateArrival = "Simulate arrival",
)