package com.example.teminavigator.ui.langs

val germanStrings = AppStrings(
    acceptButton = "Bring mich hin",
    confirmTitle = { name -> "Zu $name gehen?" },
    confirmYes = "Ja, führe mich",
    confirmNo = "Abbrechen",
    cdMap = "Etagenplan",
    cdSettings = "Einstellungen",
    cdZoomIn = "Vergrößern",
    cdZoomOut = "Verkleinern",
    settingsTitle = "Einstellungen",
    languageLabel = "Sprache",
    spokenArrived = { name -> "Wir sind bei $name angekommen." },
    spokenUnknownDestination = "Entschuldigung, dieses Ziel kenne ich nicht.",
    greeting = "Hallo, schön dich zu sehen!",
    locationQuery =  "Wo darf ich dich hinbringen?",
    selectLocation = "Ort auswählen",
    backToNavigation = "Zurück zur Navigation",
    speechNotice = "Du kannst auch sagen: \"Bring mich zu Raum 2.72\"",
    goingTo = "UNTERWEGS NACH",
    minutes = "minuten",
    pause =  "Pause",
    abortNavigation = "Navigation abbrechen",
    simulateArrival = "Ankunft simulieren",
    sounds = "Töne",
    descriptionSounds = "Hinweis- und Bestätigungstöne wiedergeben",
    voiceOutput = "Sprachausgabe",
    descriptionVoiceOutput = "Anweisungen und Ankunft laut ansagen",
    voiceInput = "Spracheingabe",
    descriptionVoiceInput = "Erlaube Spracheingabe durch Nutzer",
    autoReturn = "Automatisch zurückkehren",
    descriptionAutoReturn = "Nach 3 Minuten zum Startpunkt fahren",
)